### ISSUE TITLE
As a user I should be able to see the scores for a city.

### ISSUE THREAD

**Issue by awirth224** [awirth224/citysearch#6]
user should be able to input into the form for home and desired city
click submit- see a card that display the city image up top for both home city and desired city
below the image should be relevant information to its corresponding city.

**Comment by AndrewCerveny** [comment]
- user should be able to input into the form for home and desired city
- click submit- see  a card that display the city image up top for both home city and desired city
- below the image should be relevant information to its corresponding city.
